import { createFileRoute } from "@tanstack/react-router";
import { Github, Linkedin, Mail, MapPin, MessageCircle, Phone } from "lucide-react";
import { useState } from "react";
import { PageIntro } from "@/components/portfolio-layout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
export const Route = createFileRoute("/contact")({ head: () => ({ meta: [{ title: "Contact Sateesh Kumar Singh" }, { name: "description", content: "Contact Sateesh Kumar Singh about Agentic AI, GenAI, data, cloud consulting and technology partnerships." }, { property: "og:title", content: "Contact Sateesh Kumar Singh" }, { property: "og:description", content: "Discuss AI consulting and technology partnerships." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: Contact });
function Contact() { const [sent, setSent] = useState(false); const [failed, setFailed] = useState(false); return <section className="section-container py-16"><PageIntro eyebrow="Contact" title="Let’s build what’s next.">Open to AI/ML consulting, architecture leadership and technology partnerships.</PageIntro><div className="grid gap-8 lg:grid-cols-[1fr_340px]"><form className="glass-card space-y-5 p-6" onSubmit={async (event) => { event.preventDefault(); const formEl = event.currentTarget; const form = new FormData(formEl); try { const res = await fetch("https://pehefol.app.n8n.cloud/webhook/myresume-contact-us", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(form.entries())) }); if (!res.ok) throw new Error(String(res.status)); setSent(true); setFailed(false); formEl.reset(); } catch { setFailed(true); } }}><div><Label htmlFor="name">Name</Label><Input id="name" name="name" required className="mt-2" /></div><div><Label htmlFor="email">Email</Label><Input id="email" name="email" type="email" required className="mt-2" /></div><div><Label htmlFor="message">Message</Label><Textarea id="message" name="message" required rows={6} className="mt-2" /></div><Button type="submit">Send message</Button>{failed && <p role="alert" className="text-sm font-semibold text-destructive">Could not send your message. Please try again or email directly.</p>}{sent && <p role="status" className="text-sm font-semibold text-primary">Thank you. Your message has been sent.</p>}</form><aside className="space-y-6"><div className="glass-card p-6"><h2 className="font-bold">Direct</h2><ul className="mt-5 space-y-4 text-sm text-muted-foreground"><li><a className="flex gap-2 hover:text-primary" href="mailto:sateesh.singh76@gmail.com"><Mail className="size-4" />sateesh.singh76@gmail.com</a></li><li><a className="flex gap-2 hover:text-primary" href="tel:+919920074439"><Phone className="size-4" />+91 99200 74439</a></li><li><a className="flex gap-2 hover:text-primary" href="https://wa.me/919920074439"><MessageCircle className="size-4" />WhatsApp</a></li><li className="flex gap-2"><MapPin className="size-4" />Mumbai, India</li></ul></div><div className="glass-card p-6"><h2 className="font-bold">Online</h2><div className="mt-5 flex gap-3"><Button asChild variant="outline" size="icon"><a href="https://www.linkedin.com/in/sateesh-singh-2224b666/" aria-label="LinkedIn"><Linkedin /></a></Button><Button asChild variant="outline" size="icon"><a href="https://github.com/sateesh1976/" aria-label="GitHub"><Github /></a></Button></div></div></aside></div></section>; }